### PR TITLE
Update MENTORS.md

### PR DESCRIPTION
**Pull request by neelshah2409**
**Things added/changed**: 
- Added my name (Neel Shah) in mentor's list [Mentor.md] .

### CODE REVIEW

**Review by Panquesito7 — CHANGES_REQUESTED** [review]
Please resolve the merge conflicts [**here**](https://github.com/devstrons/devsrequests/pull/4/conflicts). Let us know if you need any help! :)

**Comment by neelshah2409** [comment]
> Please resolve the merge conflicts [**here**](https://github.com/devstrons/devsrequests/pull/4/conflicts). Let us know if you need any help! :)

Conflicts were resolved. :)

**Review by Panquesito7 — APPROVED** [review]
CC: @amino19.

**Comment by amino19** [comment]
@neelshah2409: Really apologize for being late, great to see you on boarding, feel free to join in [DEVSTR😊NS'](https://discord.gg/MVujzTBqed) discord server!

Thank you! :heart:

**Review by amino19 — APPROVED** [review]

**Pull request merged**
